SERVER_HOST = 'localhost'
SERVER_PORT = 5001

DATABASE_USERNAME = 'root'
DATABASE_PASSWORD = ''
DATABASE_HOST = 'localhost'
DATABASE_PORT = 3306
DATABASE = 'deeplearning_gallery'
DATABASE_URI = f'mysql+pymysql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE}?charset=utf8mb4'
SQLALCHEMY_DATABASE_URI = DATABASE_URI

MAIL_SERVER = 'smtp.163.com'
MAIL_USE_SSL = True
MAIL_PORT = 465
MAIL_USERNAME = "q895739647@163.com"
MAIL_PASSWORD = "OXXVFIYHEWZGWFDL"
MAIL_DEFAULT_SENDER = 'q895739647@163.com'

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1
REDIS_PASSWORD = '123456'

SECRET_KEY = 'Pineclone'
